######  db config start ######
spring:
  datasource:
    url: jdbc:mysql://47.103.7.106:3306/help?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #设置最大上传大小为10Mb
    http:
      multipart:
        max-file-size: 10Mb
server:
#  port: 8080
  port: 81
  servlet:
    context-path: /cisp/
#file:
#  path: D:/img/
#  sonPath: /img/
file:
  path: /usr/img/
  sonPath: /img/


img:
  local:
    path: /usr/img/
  Host: http://47.103.7.106:80/cisp
#img:
#  local:
#    path: D:/img/
#  Host: http://localhost:8080/cisp